/**
 * M46-A1: questSynthesisAI.ts - Procedural Quest Generation with Belief Engine
 * 
 * Bridges faction warfare, belief layer, and NPC memory to synthesize dynamically relevant quests.
 * 
 * Key features:
 * - Faction-driven questing: Losing factions need sabotage/propaganda missions
 * - Rumor investigation chains: Players discover hard facts by investigating rumors
 * - Propaganda missions: Factions pay to spread false beliefs in regions
 * - Discovery quests: When world fragments are found, generate related missions
 */

export interface ProceduralQuest {
  id: string;
  title: string;
  description: string;
  giver: string; // NPC ID or faction name
  type: "diplomacy" | "sabotage" | "investigation" | "escort" | "retrieval" | "assassination" | "propaganda" | "discovery" | "rumor_investigation";
  locationId: string;
  associatedFactionId: string;
  rewardXp: number;
  rewardGold: number;
  difficultyTier: 1 | 2 | 3 | 4 | 5;
  triggerReason: string; // Why was this quest generated?
  linkedNpcs: string[]; // NPCs involved or referenced
  linkedMemories: string[]; // memory IDs that inspired this quest
  linkedRumorIds?: string[]; // Rumors related to this quest (for rumor investigation chains)
  relatedHardFactId?: string; // The truth this quest reveals
  expiresAt: number; // tick when quest is no longer available
  isAutoGenerated: boolean;
  
  // M46-A1: Belief layer metadata
  rumorsToSpread?: string[]; // Propaganda missions: which rumors to amplify
  beliefTier?: number; // How deep into the belief layer does this quest reach?
}

export class QuestSynthesisAI {
  private questTemplates: Map<string, ProceduralQuest[]> = new Map();
  private generatedQuests: Map<string, ProceduralQuest> = new Map();
  private seededRng: any;
  private npcMemoryEngine: any; // injected dependency
  private factionWarfareEngine: any; // injected dependency
  private beliefEngine: any; // M46-A1: injected dependency
  private factionInfluenceTrend: Map<string, number> = new Map(); // track influence changes

  constructor() {
    this.initializeQuestTemplates();
  }

  /**
   * Set dependencies for quest synthesis
   */
  setDependencies(npcMemoryEngine: any, factionWarfareEngine: any, beliefEngine: any, rng: any): void {
    this.npcMemoryEngine = npcMemoryEngine;
    this.factionWarfareEngine = factionWarfareEngine;
    this.beliefEngine = beliefEngine; // M46-A1: NEW
    this.seededRng = rng;
  }

  /**
   * Initialize available quest templates by type
   */
  private initializeQuestTemplates(): void {
    // Sabotage quests - active during faction conflict
    this.questTemplates.set("sabotage", [
      {
        id: "tpl-sab-1",
        title: "Sabotage {faction} supply lines in {location}",
        description:
          "The {opposing_faction} have requested your help disrupting {faction}'s supply routes. Deal with their merchants or guards.",
        giver: "{opposing_faction}",
        type: "sabotage",
        locationId: "",
        associatedFactionId: "",
        rewardXp: 500,
        rewardGold: 250,
        difficultyTier: 2,
        triggerReason: "",
        linkedNpcs: [],
        linkedMemories: [],
        expiresAt: 0,
        isAutoGenerated: true,
      },
      {
        id: "tpl-sab-2",
        title: "Steal {faction}'s territorial documents from {location}",
        description:
          "Intel suggests {opposing_faction} keeps territorial claims in {location}. Recover them without being caught.",
        giver: "{opposing_faction}",
        type: "sabotage",
        locationId: "",
        associatedFactionId: "",
        rewardXp: 600,
        rewardGold: 300,
        difficultyTier: 3,
        triggerReason: "",
        linkedNpcs: [],
        linkedMemories: [],
        expiresAt: 0,
        isAutoGenerated: true,
      },
    ]);

    // Investigation quests - reveal faction secrets
    this.questTemplates.set("investigation", [
      {
        id: "tpl-inv-1",
        title: "Investigate {faction} activity at {location}",
        description:
          "{contact} suspects foul play. Gather evidence about {faction}'s operations in this region.",
        giver: "{contact}",
        type: "investigation",
        locationId: "",
        associatedFactionId: "",
        rewardXp: 400,
        rewardGold: 150,
        difficultyTier: 1,
        triggerReason: "",
        linkedNpcs: [],
        linkedMemories: [],
        expiresAt: 0,
        isAutoGenerated: true,
      },
      {
        id: "tpl-inv-2",
        title: "Uncover {faction}'s spies in {location}",
        description:
          "{opposing_faction} believes {faction} has planted informants here. Identify and neutralize them.",
        giver: "{opposing_faction}",
        type: "sabotage",
        locationId: "",
        associatedFactionId: "",
        rewardXp: 550,
        rewardGold: 200,
        difficultyTier: 2,
        triggerReason: "",
        linkedNpcs: [],
        linkedMemories: [],
        expiresAt: 0,
        isAutoGenerated: true,
      },
    ]);

    // Diplomacy quests - broker peace or alliances
    this.questTemplates.set("diplomacy", [
      {
        id: "tpl-dip-1",
        title: "Broker peace between {faction} and {opposing_faction} in {location}",
        description:
          "Tensions are escalating. Negotiate a temporary ceasefire and prevent bloodshed.",
        giver: "Neutral Party",
        type: "diplomacy",
        locationId: "",
        associatedFactionId: "",
        rewardXp: 750,
        rewardGold: 400,
        difficultyTier: 4,
        triggerReason: "",
        linkedNpcs: [],
        linkedMemories: [],
        expiresAt: 0,
        isAutoGenerated: true,
      },
      {
        id: "tpl-dip-2",
        title: "Deliver ultimatum from {faction} to {opposing_faction}",
        description:
          "{faction} needs you to personally warn {opposing_faction}'s leaders.",
        giver: "{faction}",
        type: "diplomacy",
        locationId: "",
        associatedFactionId: "",
        rewardXp: 500,
        rewardGold: 200,
        difficultyTier: 3,
        triggerReason: "",
        linkedNpcs: [],
        linkedMemories: [],
        expiresAt: 0,
        isAutoGenerated: true,
      },
    ]);

    // Assassination quests - eliminate key figures
    this.questTemplates.set("assassination", [
      {
        id: "tpl-ass-1",
        title: "Eliminate {target} from {faction}",
        description:
          "With {target} gone, the balance of power shifts. {faction} has placed a substantial bounty.",
        giver: "Assassination Broker",
        type: "assassination",
        locationId: "",
        associatedFactionId: "",
        rewardXp: 1000,
        rewardGold: 600,
        difficultyTier: 5,
        triggerReason: "",
        linkedNpcs: [],
        linkedMemories: [],
        expiresAt: 0,
        isAutoGenerated: true,
      },
    ]);

    // Escort/Retrieval quests - rescue or transport
    this.questTemplates.set("escort", [
      {
        id: "tpl-esc-1",
        title: "Escort {faction}'s emissary safely to {location}",
        description:
          "Hostilities are high. {faction} needs a trusted neutral party to accompany their representative.",
        giver: "{faction}",
        type: "escort",
        locationId: "",
        associatedFactionId: "",
        rewardXp: 550,
        rewardGold: 300,
        difficultyTier: 3,
        triggerReason: "",
        linkedNpcs: [],
        linkedMemories: [],
        expiresAt: 0,
        isAutoGenerated: true,
      },
    ]);

    // M46-A1: Propaganda quests - spread rumors and false beliefs
    this.questTemplates.set("propaganda", [
      {
        id: "tpl-prop-1",
        title: "Spread the word: {faction} is faltering in {location}",
        description:
          "{opposing_faction} wants rumors to circulate that {faction} is losing their grip. Speak to NPCs, drop hints, let the belief spread naturally.",
        giver: "{opposing_faction}",
        type: "propaganda",
        locationId: "",
        associatedFactionId: "",
        rewardXp: 400,
        rewardGold: 200,
        difficultyTier: 2,
        triggerReason: "Faction losing influence - needs rumor propagation",
        linkedNpcs: [],
        linkedMemories: [],
        expiresAt: 0,
        isAutoGenerated: true,
      },
      {
        id: "tpl-prop-2",
        title: "Counter the false narrative about {faction}",
        description:
          "{faction} is suffering from a PR crisis. Convince key NPCs that the rumors are lies. Rebuild their reputation.",
        giver: "{faction}",
        type: "propaganda",
        locationId: "",
        associatedFactionId: "",
        rewardXp: 450,
        rewardGold: 250,
        difficultyTier: 3,
        triggerReason: "Faction reputation damage - needs pr correction",
        linkedNpcs: [],
        linkedMemories: [],
        expiresAt: 0,
        isAutoGenerated: true,
      },
    ]);

    // M46-A1: Rumor Investigation quests - discover hard facts via belief layer
    this.questTemplates.set("rumor_investigation", [
      {
        id: "tpl-rum-1",
        title: "Investigate the rumor about {faction} in {location}",
        description:
          "Whispers suggest {faction} is hiding something in {location}. {contact} wants the truth. Seek out NPCs, explore the area, and separate fact from fiction.",
        giver: "{contact}",
        type: "rumor_investigation",
        locationId: "",
        associatedFactionId: "",
        rewardXp: 500,
        rewardGold: 250,
        difficultyTier: 2,
        triggerReason: "Rumor spreading - investigate to reveal hard fact",
        linkedNpcs: [],
        linkedMemories: [],
        expiresAt: 0,
        isAutoGenerated: true,
      },
      {
        id: "tpl-rum-2",
        title: "Uncover what really happened to {faction} at {location}",
        description:
          "Everyone's talking about a mysterious event. Find witnesses, gather evidence, and learn what truly occurred.",
        giver: "Curious Scholar",
        type: "rumor_investigation",
        locationId: "",
        associatedFactionId: "",
        rewardXp: 600,
        rewardGold: 300,
        difficultyTier: 3,
        triggerReason: "Major rumor spreading - need fact discovery",
        linkedNpcs: [],
        linkedMemories: [],
        expiresAt: 0,
        isAutoGenerated: true,
      },
    ]);

    // M46-A1: Discovery quests - related to world fragments and historical sites
    this.questTemplates.set("discovery", [
      {
        id: "tpl-disc-1",
        title: "Explore the ruins of {location}",
        description:
          "Once, {faction} held {location}. Now it lies in ruins. Venture there and uncover what remains of their legacy.",
        giver: "{contact}",
        type: "discovery",
        locationId: "",
        associatedFactionId: "",
        rewardXp: 550,
        rewardGold: 280,
        difficultyTier: 2,
        triggerReason: "World fragment discovered - generate exploration quest",
        linkedNpcs: [],
        linkedMemories: [],
        expiresAt: 0,
        isAutoGenerated: true,
      },
      {
        id: "tpl-disc-2",
        title: "Retrieve artifact from the forgotten {location}",
        description:
          "{faction} lost something of immense value when {location} fell. Retrieve it, if you can survive the dangers.",
        giver: "{faction}",
        type: "discovery",
        locationId: "",
        associatedFactionId: "",
        rewardXp: 700,
        rewardGold: 400,
        difficultyTier: 4,
        triggerReason: "Historical significance - legacy recovery",
        linkedNpcs: [],
        linkedMemories: [],
        expiresAt: 0,
        isAutoGenerated: true,
      },
    ]);

    // Phase 28 Task 1: Economic quests - tied to BOOM/STABLE/RECESSION cycles
    this.questTemplates.set("economic", [
      {
        id: "tpl-econ-1",
        title: "Escort merchant caravan through {location}",
        description:
          "Business is booming! A merchant caravan needs protection as they travel through {location}. Defend them from bandits and competitors.",
        giver: "Caravan Master",
        type: "escort",
        locationId: "",
        associatedFactionId: "",
        rewardXp: 300,
        rewardGold: 400,
        difficultyTier: 2,
        triggerReason: "Economic expansion - BOOM cycle caravan escort",
        linkedNpcs: [],
        linkedMemories: [],
        expiresAt: 0,
        isAutoGenerated: true,
      },
      {
        id: "tpl-econ-2",
        title: "Help refugees find shelter in {location}",
        description:
          "The economic downturn has left many homeless. Find them safe refuge and supplies. Reward: reputation and NPC gratitude.",
        giver: "Local Charity Leader",
        type: "retrieval",
        locationId: "",
        associatedFactionId: "",
        rewardXp: 600,
        rewardGold: 150,
        difficultyTier: 2,
        triggerReason: "Economic hardship - RECESSION cycle aid mission",
        linkedNpcs: [],
        linkedMemories: [],
        expiresAt: 0,
        isAutoGenerated: true,
      },
      {
        id: "tpl-econ-3",
        title: "Investigate missing supply shipment",
        description:
          "A supply shipment never arrived at {location}. Track it down and recover what you can. The merchants will pay handsomely.",
        giver: "Trade Master",
        type: "investigation",
        locationId: "",
        associatedFactionId: "",
        rewardXp: 400,
        rewardGold: 350,
        difficultyTier: 2,
        triggerReason: "Trade disruption - economic investigation",
        linkedNpcs: [],
        linkedMemories: [],
        expiresAt: 0,
        isAutoGenerated: true,
      },
    ]);

    // Phase 28 Task 1: Paradox quests - tied to Age Rot zones and paradox points
    this.questTemplates.set("paradox", [
      {
        id: "tpl-par-1",
        title: "Stabilize the reality distortion at {location}",
        description:
          "Reality itself is breaking down at {location}. Anomalous creatures and impossible physics create danger for all. Restore balance by solving the paradoxes.",
        giver: "Reality Warden",
        type: "investigation",
        locationId: "",
        associatedFactionId: "",
        rewardXp: 800,
        rewardGold: 250,
        difficultyTier: 4,
        triggerReason: "High paradox level - reality stabilization needed",
        linkedNpcs: [],
        linkedMemories: [],
        expiresAt: 0,
        isAutoGenerated: true,
      },
      {
        id: "tpl-par-2",
        title: "Seal the Age Rot zone in {location}",
        description:
          "An area has fallen into temporal decay. Time itself crumbles. You must find anchors of temporal stability and seal this wound before it spreads.",
        giver: "Temporal Sage",
        type: "retrieval",
        locationId: "",
        associatedFactionId: "",
        rewardXp: 900,
        rewardGold: 300,
        difficultyTier: 5,
        triggerReason: "Critical Age Rot - containment required",
        linkedNpcs: [],
        linkedMemories: [],
        expiresAt: 0,
        isAutoGenerated: true,
      },
    ]);
  }

  /**
   * Instantiate a quest template with specific parameters
   */
  private instantiateTemplate(
    template: ProceduralQuest,
    locationId: string,
    currentTick: number,
    expiryTicks: number,
    npcGiver: string,
    dominantFactionId: string,
    opposingFactionId?: string
  ): ProceduralQuest {
    // Create a unique ID for this quest instance
    const questId = `quest_${template.id}_${locationId}_${currentTick}_${Math.random().toString(36).substr(2, 9)}`;

    // Replace placeholders in title and description
    let title = template.title
      .replace(/{location}/g, locationId)
      .replace(/{faction}/g, dominantFactionId)
      .replace(/{opposing_faction}/g, opposingFactionId || 'opposing_faction')
      .replace(/{target}/g, 'target') // TODO: get actual target
      .replace(/{contact}/g, npcGiver);

    let description = template.description
      .replace(/{location}/g, locationId)
      .replace(/{faction}/g, dominantFactionId)
      .replace(/{opposing_faction}/g, opposingFactionId || 'opposing_faction')
      .replace(/{target}/g, 'target') // TODO: get actual target
      .replace(/{contact}/g, npcGiver);

    // Create the instantiated quest
    const quest: ProceduralQuest = {
      ...template,
      id: questId,
      title,
      description,
      giver: npcGiver,
      locationId,
      associatedFactionId: dominantFactionId,
      expiresAt: currentTick + expiryTicks,
      linkedNpcs: [npcGiver],
    };

    return quest;
  }

  /**
   * Generate quests based on current world state
   * Called during epoch transitions or faction skirmishes
   */
  synthesizeQuestsFromWarfare(
    locationId: string,
    warZoneStatus: any, // from factionWarfareEngine
    nearbyNpcs: string[],
    currentTick: number,
    expiryTicks: number = 5000
  ): ProceduralQuest[] {
    const generatedQuests: ProceduralQuest[] = [];

    if (!this.factionWarfareEngine) {
      console.warn("[QuestSynthesisAI] Faction warfare engine not initialized");
      return [];
    }

    const recentSkirmishes = warZoneStatus.recentSkirmishes || [];
    const contentionLevel = warZoneStatus.contentionLevel || 0;

    // Generate quests based on contention level
    if (contentionLevel > 0.5) {
      // Highly contested - generate sabotage/investigation
      const templates =
        this.questTemplates.get(this.seededRng?.next(currentTick) % 2 === 0 ? "sabotage" : "investigation") ||
        [];

      for (const npcId of nearbyNpcs.slice(0, 2)) {
        if (templates.length > 0) {
          const template = templates[0];
          const quest = this.instantiateTemplate(
            template,
            locationId,
            currentTick,
            expiryTicks,
            npcId,
            warZoneStatus.currentDominant
          );
          generatedQuests.push(quest);
        }
      }
    }

    if (contentionLevel > 0.7 && recentSkirmishes.length > 0) {
      // Very contested - add diplomacy or peace quests
      const dipTemplates = this.questTemplates.get("diplomacy") || [];
      if (dipTemplates.length > 0) {
        const template = dipTemplates[0];
        const quest = this.instantiateTemplate(
          template,
          locationId,
          currentTick,
          expiryTicks,
          "Neutral Broker",
          warZoneStatus.currentDominant
        );
        generatedQuests.push(quest);
      }
    }

    return generatedQuests;
  }

  /**
   * Generate quests from NPC social scars (grievances)
   */
  synthesizeQuestsFromMemory(npcId: string, currentTick: number): ProceduralQuest[] {
    const generatedQuests: ProceduralQuest[] = [];

    if (!this.npcMemoryEngine) {
      console.warn("[QuestSynthesisAI] NPC Memory engine not initialized");
      return [];
    }

    const memoryImpact = this.npcMemoryEngine.getMemoryImpactOnDialogue(npcId, "player");
    if (!memoryImpact) return [];

    // If NPC has strong grudge, generate vengeance quest
    if (memoryImpact.cautionLevel > 0.6) {
      const grudgeQuest: ProceduralQuest = {
        id: `quest-grudge-${npcId}-${currentTick}`,
        title: `Resolve conflict with ${npcId}`,
        description: `${npcId} has been harboring resentment. Perhaps completing a task for them would rebuild trust.`,
        giver: npcId,
        type: "diplomacy",
        locationId: "unknown",
        associatedFactionId: "none",
        rewardXp: 300,
        rewardGold: 100,
        difficultyTier: 1,
        triggerReason: `NPC grudge against player (caution: ${memoryImpact.cautionLevel})`,
        linkedNpcs: [npcId],
        linkedMemories: [],
        expiresAt: currentTick + 2000,
        isAutoGenerated: true,
      };
      generatedQuests.push(grudgeQuest);
    }

    // If NPC has strong favor, generate collaborative quest
    if (memoryImpact.trustLevel > 0.7) {
      const favorQuest: ProceduralQuest = {
        id: `quest-favor-${npcId}-${currentTick}`,
        title: `Help ${npcId} with a special task`,
        description: `${npcId} clearly trusts you. They have a favor to ask...`,
        giver: npcId,
        type: "retrieval",
        locationId: "unknown",
        associatedFactionId: "none",
        rewardXp: 400,
        rewardGold: 200,
        difficultyTier: 2,
        triggerReason: `NPC trust/favor (trust: ${memoryImpact.trustLevel})`,
        linkedNpcs: [npcId],
        linkedMemories: [],
        expiresAt: currentTick + 3000,
        isAutoGenerated: true,
      };
      generatedQuests.push(favorQuest);
    }

    return generatedQuests;
  }

  /**
   * M46-A1: Generate quests from faction influence losses
   * When a faction's influence drops significantly, they purchase propaganda/recovery missions
   */
  synthesizeQuestsFromFactionInfluence(
    locationId: string,
    allFactions: string[],
    currentTick: number,
    locationControl: any // from factionWarfareEngine.getLocationControl()
  ): ProceduralQuest[] {
    const generatedQuests: ProceduralQuest[] = [];

    if (!locationControl) return [];

    // Check each faction's influence trend
    for (const factionId of allFactions) {
      const influenceKey = `${locationId}_${factionId}`;
      const previousInfluence = this.factionInfluenceTrend.get(influenceKey) || 0;
      const currentInfluence = locationControl.factionInfluence?.[factionId] || 0;
      const influenceDelta = currentInfluence - previousInfluence;

      // Store current influence for next check
      this.factionInfluenceTrend.set(influenceKey, currentInfluence);

      // If faction is losing influence (delta < -0.1), generate recovery quests
      if (influenceDelta < -0.15) {
        const templates = this.questTemplates.get("propaganda") || [];
        
        if (templates.length > 0 && currentInfluence < 0.4) {
          // Critical influence loss: need propaganda or sabotage
          const template = templates[0];
          const quest = this.instantiateTemplate(
            template,
            locationId,
            currentTick,
            2000, // propaganda missions expire faster
            `${factionId} Operative`,
            factionId,
            this.findOpposingFaction(factionId, allFactions)
          );

          // M46-A1: Add belief layer metadata
          quest.rumorsToSpread = this.generatePropagandaRumors(
            locationId,
            factionId,
            currentInfluence
          );
          quest.beliefTier = 2;

          generatedQuests.push(quest);
        }
      }

      // If faction is gaining influence, enemy factions counter with sabotage
      if (influenceDelta > 0.15) {
        const opposingFactionId = this.findOpposingFaction(factionId, allFactions);
        const templates = this.questTemplates.get("sabotage") || [];

        if (templates.length > 0) {
          const template = templates[0];
          const quest = this.instantiateTemplate(
            template,
            locationId,
            currentTick,
            2000,
            `${opposingFactionId} Saboteur`,
            opposingFactionId,
            factionId
          );

          generatedQuests.push(quest);
        }
      }
    }

    return generatedQuests;
  }

  /**
   * M46-A1: Find an opposing/rival faction
   */
  private findOpposingFaction(factionId: string, allFactions: string[]): string {
    const factionRivals: Record<string, string> = {
      'Silver Flame': 'Shadow Conclave',
      'Shadow Conclave': 'Silver Flame',
      'Holy Order': 'Merchant Guild',
      'Merchant Guild': 'Holy Order'
    };

    return factionRivals[factionId] || allFactions.find(f => f !== factionId) || 'Unknown';
  }

  /**
   * M46-A1: Generate propaganda rumors for a mission
   */
  private generatePropagandaRumors(
    locationId: string,
    factionId: string,
    influenceLevel: number
  ): string[] {
    const rumors: string[] = [];

    if (influenceLevel < 0.3) {
      rumors.push(`${factionId} is crumbling in ${locationId}`);
      rumors.push(`${factionId}'s power in ${locationId} is mere shadow`);
      rumors.push(`Have you heard? ${factionId} abandoned ${locationId}`);
    } else if (influenceLevel < 0.5) {
      rumors.push(`${factionId} is struggling to hold ${locationId}`);
      rumors.push(`Whispers say ${factionId} lost control of key locations in ${locationId}`);
    }

    return rumors;
  }

  /**
   * M46-A1: Synthesize investigation quests from active rumors
   * Creates chains: Rumor → Investigation → Hard Fact discovery
   */
  synthesizeQuestsFromRumors(
    locationId: string,
    playerPerceptionLevel: number,
    currentTick: number
  ): ProceduralQuest[] {
    const generatedQuests: ProceduralQuest[] = [];

    if (!this.beliefEngine) {
      console.warn("[QuestSynthesisAI] Belief engine not initialized for rumor synthesis");
      return [];
    }

    // Get rumors available at this location
    const rumors = this.beliefEngine.getRumorsAtLocation(
      locationId,
      'player', // Neutral faction for query
      playerPerceptionLevel
    );

    // Create investigation quest for each high-confidence rumor
    rumors.forEach((rumor: any, index: number) => {
      if (rumor.confidenceLevel < 40) return; // Skip low-confidence rumors

      const templates = this.questTemplates.get("rumor_investigation") || [];
      if (templates.length === 0) return;

      const template = templates[index % templates.length];
      const quest = this.instantiateTemplate(
        template,
        locationId,
        currentTick,
        3000, // Investigation quests last longer
        'Curious Scholar',
        rumor.claimedFactionIds?.[0] || 'Unknown',
        rumor.claimedFactionIds?.[1] || undefined
      );

      // M46-A1: Link this quest to the rumor and its hard fact
      quest.linkedRumorIds = [rumor.id];
      quest.relatedHardFactId = rumor.originalFactId;
      quest.beliefTier = 1; // Veiled tier - starts with rumors

      generatedQuests.push(quest);
    });

    return generatedQuests;
  }

  /**
   * M46-A1: Generate discovery quests from world fragments
   * When a location has historical significance, create quests to explore it
   */
  synthesizeQuestsFromWorldFragments(
    locationId: string,
    worldFragments: any[], // from chronicleEngine
    currentTick: number
  ): ProceduralQuest[] {
    const generatedQuests: ProceduralQuest[] = [];

    if (!worldFragments || worldFragments.length === 0) {
      return generatedQuests;
    }

    // Filter fragments relevant to this location
    const relevantFragments = worldFragments.filter(f => f.locationId === locationId);

    relevantFragments.forEach((fragment, index) => {
      const templates = this.questTemplates.get("discovery") || [];
      if (templates.length === 0) return;

      const template = templates[index % templates.length];
      
      // Determine if this is ruins, shrine, tomb, or other
      let questGiver = 'Local Scholar';
      let difficulty = 2;

      switch (fragment.type) {
        case 'ruin':
          questGiver = 'Adventurer';
          difficulty = 2;
          break;
        case 'shrine':
          questGiver = 'Priest of Unknown Faith';
          difficulty = 1;
          break;
        case 'tomb':
          questGiver = 'Tomb Raider';
          difficulty = 4;
          break;
        case 'statue':
        case 'monument':
          questGiver = 'Historian';
          difficulty = 1;
          break;
      }

      const quest = this.instantiateTemplate(
        template,
        locationId,
        currentTick,
        5000, // Discovery quests are long-term
        questGiver,
        fragment.historicalEvent?.factionIds?.[0] || 'Ancient Power'
      );

      quest.difficultyTier = difficulty as any;
      quest.triggerReason = `World fragment discovered: ${fragment.name} (type: ${fragment.type})`;
      quest.linkedMemories = [fragment.historicalEvent?.id || ''];

      generatedQuests.push(quest);
    });

    return generatedQuests;
  }

  /**
   * Phase 28 Task 1: Synthesize quests based on economic cycles
   * BOOM cycle → high-reward merchant quests
   * RECESSION → aid/investigation quests
   * STABLE → trade route quests
   */
  synthesizeEconomicQuests(
    state: any, // WorldState
    currentTick: number
  ): ProceduralQuest[] {
    const generatedQuests: ProceduralQuest[] = [];

    if (!state?.player?.locationId) return [];

    const locationId = state.player.locationId;
    const economyScore = state.telemetryState?.economyHealth ?? 50; // Default to stable

    // Determine economic cycle
    let cycle: 'BOOM' | 'STABLE' | 'RECESSION';
    if (economyScore > 75) {
      cycle = 'BOOM';
    } else if (economyScore < 25) {
      cycle = 'RECESSION';
    } else {
      cycle = 'STABLE';
    }

    // Select quest templates based on economic cycle
    const templates = this.questTemplates.get("economic") || [];
    if (templates.length === 0) return [];

    let selectedTemplate: ProceduralQuest | null = null;
    let expiryTicks = 2000;
    let questGiver = "Merchant";
    let dominantFactionId = "Merchants Guild";

    switch (cycle) {
      case 'BOOM':
        // Caravan escort quest - high gold reward, low XP
        selectedTemplate = templates[0];
        expiryTicks = 3000; // Caravans move relatively fast
        questGiver = "Caravan Master";
        break;
      case 'RECESSION':
        // Aid/investigation quest - high XP reward, low gold
        selectedTemplate = templates[1];
        expiryTicks = 5000; // Longer to help refugees
        questGiver = "Local Charity Leader";
        dominantFactionId = "Humanitarian Coalition";
        break;
      case 'STABLE':
        // Investigation quest - balanced rewards
        selectedTemplate = templates[2];
        expiryTicks = 4000;
        questGiver = "Trade Master";
        break;
    }

    if (selectedTemplate) {
      const quest = this.instantiateTemplate(
        selectedTemplate,
        locationId,
        currentTick,
        expiryTicks,
        questGiver,
        dominantFactionId
      );

      quest.triggerReason = `Economic cycle: ${cycle} (score: ${economyScore.toFixed(0)}/100)`;
      quest.linkedMemories = []; // Could link to relevant economic events

      generatedQuests.push(quest);
    }

    return generatedQuests;
  }

  /**
   * Phase 28 Task 1: Synthesize quests based on paradox level
   * High paradox (>75) → Reality stabilization quests
   * Critical paradox (>50) → Age Rot containment quests
   */
  synthesizeParadoxQuests(
    state: any, // WorldState
    currentTick: number
  ): ProceduralQuest[] {
    const generatedQuests: ProceduralQuest[] = [];

    if (!state?.paradoxState?.totalParadoxPoints || !state?.player?.locationId) {
      return [];
    }

    const locationId = state.player.locationId;
    const paradoxLevel = state.paradoxState.totalParadoxPoints;

    // Only generate paradox quests if paradox is significant
    if (paradoxLevel < 50) {
      return [];
    }

    const templates = this.questTemplates.get("paradox") || [];
    if (templates.length === 0) return [];

    let selectedTemplate: ProceduralQuest | null = null;
    let expiryTicks = 3000;
    let questGiver = "Reality Warden";

    if (paradoxLevel > 75) {
      // CRITICAL: Reality distortion is severe
      selectedTemplate = templates[0];
      expiryTicks = 5000; // More time needed for complex stabilization
      questGiver = "Reality Warden";
    } else if (paradoxLevel > 50) {
      // SIGNIFICANT: Age Rot spreading
      selectedTemplate = templates[1];
      expiryTicks = 6000; // Seal quests are long
      questGiver = "Temporal Sage";
    }

    if (selectedTemplate) {
      const quest = this.instantiateTemplate(
        selectedTemplate,
        locationId,
        currentTick,
        expiryTicks,
        questGiver,
        'Ancient Powers' // Faction: representing reality itself
      );

      quest.triggerReason = `Critical paradox level: ${paradoxLevel.toFixed(0)} points`;
      quest.linkedMemories = state.paradoxState?.anomalies?.map((a: any) => a.id) || [];

      // High difficulty for high paradox
      if (paradoxLevel > 90) {
        quest.difficultyTier = 5;
      }

      generatedQuests.push(quest);
    }

    return generatedQuests;
  }

  /**
   * Phase 28 Task 1: Synthesize narrative quests from recent social scars
   * Links to Phase 26 social events for narrative continuity
   */
  synthesizeNarrativeQuestsFromScars(
    state: any, // WorldState
    currentTick: number
  ): ProceduralQuest[] {
    const generatedQuests: ProceduralQuest[] = [];

    if (!state?.player?.locationId || !this.npcMemoryEngine) {
      return [];
    }

    const locationId = state.player.locationId;

    // Get recent social scars from mutation log (Phase 26 social events)
    const events = state.events?.filter((e: any) =>
      e.type === 'SOCIAL_OUTBURST' && e.timestamp > currentTick - 1000
    ) || [];

    // For each recent outburst, create a related narrative quest
    events.slice(0, 2).forEach((event: any, idx: number) => {
      const template = this.questTemplates.get("investigation")?.[idx % 2];
      if (!template) return;

      const questType = event.payload?.severity > 0.7 ? 'Vengeance' : 'Rebuilding';
      const questGiver = event.payload?.npcId ? `Survivor of the Outburst` : 'Community Leader';

      const quest = this.instantiateTemplate(
        template,
        locationId,
        currentTick,
        4000, // Medium duration
        questGiver,
        event.payload?.factionId || 'Affected Faction'
      );

      quest.title = `${questType} Quest: ${event.payload?.description || 'Aftermath'}`;
      quest.description = `Following the recent outburst, the community needs ${ questType === 'Vengeance' ? 'justice' : 'help recovering'}.`;
      quest.triggerReason = `Social scar from recent outburst (id: ${event.id})`;
      quest.linkedMemories = [event.id];

      generatedQuests.push(quest);
    });

    return generatedQuests;
  }

  /**
   * Phase 29 Task 2: Synthesize "Time Repair" quests to heal world paradox
   * Generated when paradox level is moderate-to-high (>40 points)
   * Completing these quests reduces global totalParadoxPoints
   */
  synthesizeTimeRepairQuests(
    state: any, // WorldState
    currentTick: number
  ): ProceduralQuest[] {
    const generatedQuests: ProceduralQuest[] = [];

    if (!state?.paradoxState?.totalParadoxPoints || !state?.player?.locationId) {
      return [];
    }

    const locationId = state.player.locationId;
    const paradoxLevel = state.paradoxState.totalParadoxPoints;

    // Only generate time repair quests if paradox is at moderate-to-high level
    if (paradoxLevel < 40) {
      return [];
    }

    // Create "Time Repair" quest template dynamically
    const repairQuest: ProceduralQuest = {
      id: `time-repair-${currentTick}`,
      title: paradoxLevel > 75 
        ? 'The Rift Deepens: Seal the Temporal Tear'
        : 'Temporal Instability: Restore Causal Flow',
      description: paradoxLevel > 75
        ? 'Reality itself fractures under accumulated temporal debt. Ancient seals must be reactivated to restore causality.'
        : 'Minor distortions in the timeline threaten existential collapse. Meditation and rune work may restore balance.',
      type: 'time_repair' as any,
      locationId,
      givenBy: 'Temporal Sage',
      objectives: [
        {
          type: 'investigate',
          description: 'Investigate temporal anomalies',
          locationId,
          completed: false
        },
        {
          type: 'gather',
          description: 'Collect causality fragments',
          itemId: 'causality_shard',
          targetCount: paradoxLevel > 75 ? 10 : 5,
          currentCount: 0
        }
      ],
      rewards: {
        gold: Math.floor(100 + (paradoxLevel * 2)),
        experience: Math.floor(50 + (paradoxLevel * 1.5)),
        reputation: {
          'Ancient Powers': 20,
          'Temporal Keepers': 15
        }
      },
      difficulty: paradoxLevel > 75 ? 5 : (paradoxLevel > 50 ? 4 : 3),
      expiresAt: currentTick + (paradoxLevel > 75 ? 8000 : 5000),
      createdAt: currentTick,
      status: 'available',
      triggerReason: `Paradox level critical: ${paradoxLevel.toFixed(0)} points detected`,
      linkedMemories: state.paradoxState?.anomalies?.map((a: any) => a.id) || [],
      factionId: 'Ancient Powers',
      difficultyTier: paradoxLevel > 75 ? 5 : (paradoxLevel > 50 ? 4 : 3)
    };

    // Add "completion_reduces_paradox" flag for quest system integration
    (repairQuest as any).completionEffect = {
      type: 'reduce_paradox_points',
      amount: Math.floor(paradoxLevel * 0.3) // Reduce 30% of current paradox on completion
    };

    generatedQuests.push(repairQuest);

    return generatedQuests;
  }

  /**
   * M46-A1: Integrated synthesis - combines all sources
   * Call this when updating available quests (e.g., every 500 ticks)
   * Phase 28 Task 1: Now also includes economic and paradox quest synthesis
   */
  synthesizeAllQuestsForWorld(
    state: any, // WorldState
    allFactions: string[],
    currentTick: number
  ): ProceduralQuest[] {
    const newQuests: ProceduralQuest[] = [];

    if (!state?.player?.location) return [];

    const locationId = state.player.location;

    // 1. Faction influence changes → propaganda/recovery quests
    const locationControl = this.factionWarfareEngine?.getLocationControl?.(locationId);
    if (locationControl) {
      const influenceQuests = this.synthesizeQuestsFromFactionInfluence(
        locationId,
        allFactions,
        currentTick,
        locationControl
      );
      newQuests.push(...influenceQuests);
    }

    // 2. Active rumors → investigation quests
    const playerPerceptionLevel = this.beliefEngine?.calculatePerceptionLevel(
      state.player.id,
      state
    )?.level || 0;

    const rumorQuests = this.synthesizeQuestsFromRumors(
      locationId,
      playerPerceptionLevel,
      currentTick
    );
    newQuests.push(...rumorQuests);

    // 3. World fragments → discovery quests
    const worldFragments = this.beliefEngine?.getRegistry?.()?.worldFragments || [];
    const discoveryQuests = this.synthesizeQuestsFromWorldFragments(
      locationId,
      worldFragments,
      currentTick
    );
    newQuests.push(...discoveryQuests);

    // Phase 28 Task 1: Economic quests based on BOOM/STABLE/RECESSION cycles
    const economicQuests = this.synthesizeEconomicQuests(state, currentTick);
    newQuests.push(...economicQuests);

    // Phase 28 Task 1: Paradox quests for high paradox zones
    const paradoxQuests = this.synthesizeParadoxQuests(state, currentTick);
    newQuests.push(...paradoxQuests);

    // Phase 28 Task 1: Narrative quests from recent social scars
    const narrativeQuests = this.synthesizeNarrativeQuestsFromScars(state, currentTick);
    newQuests.push(...narrativeQuests);

    // Phase 29 Task 2: Time repair quests to heal world paradox
    const timeRepairQuests = this.synthesizeTimeRepairQuests(state, currentTick);
    newQuests.push(...timeRepairQuests);

    // 4. Register all new quests
    newQuests.forEach(q => this.registerGeneratedQuest(q));

    // 5. Clean up expired quests
    this.pruneExpiredQuests(currentTick);

    return newQuests;
  }

  /**
   * Register a generated quest to available pool
   */
  registerGeneratedQuest(quest: ProceduralQuest): void {
    this.generatedQuests.set(quest.id, quest);
  }

  /**
   * Get available quests
   */
  getAvailableQuests(currentTick: number): ProceduralQuest[] {
    return Array.from(this.generatedQuests.values()).filter(
      (q) => q.expiresAt > currentTick
    );
  }

  /**
   * Clean up expired quests
   */
  pruneExpiredQuests(currentTick: number): void {
    for (const [id, quest] of this.generatedQuests.entries()) {
      if (quest.expiresAt <= currentTick) {
        this.generatedQuests.delete(id);
      }
    }
  }

  /**
   * Export synthesis state for debugging
   */
  exportSynthesisState(): object {
    return {
      generatedQuestCount: this.generatedQuests.size,
      questsByType: Array.from(this.generatedQuests.values()).reduce(
        (acc, q) => {
          acc[q.type] = (acc[q.type] || 0) + 1;
          return acc;
        },
        {} as Record<string, number>
      ),
      recentQuests: Array.from(this.generatedQuests.values())
        .slice(-10)
        .map((q) => ({
          id: q.id,
          title: q.title,
          giver: q.giver,
          type: q.type,
        })),
    };
  }

  /**
   * Clear all generated quests (for testing)
   */
  clearState(): void {
    this.generatedQuests.clear();
    this.factionInfluenceTrend.clear();
  }
}

// Singleton instance
let instance: QuestSynthesisAI | null = null;

export function getQuestSynthesisAI(): QuestSynthesisAI {
  if (!instance) {
    instance = new QuestSynthesisAI();
  }
  return instance;
}

/**
 * Initialize quest synthesis with all dependencies
 * Call this during world engine startup
 */
export function initializeQuestSynthesis(
  npcMemoryEngine: any,
  factionWarfareEngine: any,
  beliefEngine: any,
  rng: any
): void {
  const synthesisAI = getQuestSynthesisAI();
  synthesisAI.setDependencies(npcMemoryEngine, factionWarfareEngine, beliefEngine, rng);
}

