import React, { useState, useMemo } from 'react';
import type { WorldState } from '../../engine/worldEngine';
import { generateAtmosphericText, generateVisualPrompt, type VisualPrompt } from '../../engine/assetGenerator';

/**
 * OracleView Component - Part of M14 "The Shifting Mirror"
 * 
 * Displays deterministic scene descriptions generated by assetGenerator
 * Renders atmospheric text, visual prompts, and narrative threads
 * 
 * Props:
 *   state: Current world state for context
 *   isDeveloperMode: Show generation timestamps and seed info
 */

interface OracleViewProps {
  state: WorldState;
  isDeveloperMode?: boolean;
}

interface AtmosphericContent {
  atmospheric: string;
  visual: VisualPrompt | null;
  generatedAt: number;
  seed?: string;
}

const OracleView: React.FC<OracleViewProps> = ({ state, isDeveloperMode = false }) => {
  const [activePanel, setActivePanel] = useState<'atmosphere' | 'visual' | 'narrative'>('atmosphere');
  const [contentHistory, setContentHistory] = useState<AtmosphericContent[]>([]);

  // Generate content whenever state changes significantly
  const generatedContent = useMemo(() => {
    const atmospheric = generateAtmosphericText(state);
    
    // Build visual prompt context
    const playerLocation = state.locations?.find((l: any) => l.id === state.player.location);
    const hour = state.hour ?? 12; // Phase 6: Direct property access (no type assertion)
    
    const getDayPhase = () => {
      if (hour >= 6 && hour < 12) return 'morning';
      if (hour >= 12 && hour < 18) return 'afternoon';
      if (hour >= 18 && hour < 21) return 'evening';
      return 'night';
    };
    
    // Phase 6: Use weather directly (string literal, not object)
    const visualContext = {
      weather: state.weather ?? 'clear',
      season: state.season ?? 'spring',
      time: `hour-${hour}`,
      dayPhase: getDayPhase(),
      location: playerLocation || { id: 'unknown', name: 'Unknown', biome: 'forest' as const, features: [], connected: [] }
    };
    
    const visual = generateVisualPrompt(state, visualContext);

    const content: AtmosphericContent = {
      atmospheric,
      visual,
      generatedAt: Date.now(),
      seed: state.seed?.toString() ?? 'unknown' // Phase 6: Use seed from WorldState
    };

    // Keep last 10 generations in history for reference
    setContentHistory(prev => [content, ...prev].slice(0, 10));

    return content;
  }, [
    state.tick,
    state.player.location,
    state.hour, // Phase 6: Direct property reference
    state.weather // Phase 6: Direct property reference
  ]);

  const styles = {
    container: {
      display: 'flex',
      flexDirection: 'column' as const,
      width: '100%',
      height: '100%',
      backgroundColor: '#0a0a14',
      borderLeft: '2px solid #0f3',
      fontFamily: 'monospace' as const,
      color: '#e0e0e0'
    },
    header: {
      padding: '12px 16px',
      borderBottom: '1px solid #0f3',
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      fontSize: '14px',
      fontWeight: 'bold' as const,
      textTransform: 'uppercase' as const,
      letterSpacing: '2px'
    },
    tabBar: {
      display: 'flex',
      gap: '4px',
      padding: '8px 12px',
      borderBottom: '1px solid #1a1a2e',
      backgroundColor: '#0f0f18'
    },
    tab: (active: boolean) => ({
      padding: '6px 12px',
      border: `1px solid ${active ? '#0f3' : '#333'}`,
      backgroundColor: active ? '#0f3' : 'transparent',
      color: active ? '#000' : '#888',
      cursor: 'pointer' as const,
      fontSize: '12px',
      fontWeight: active ? 'bold' as const : 'normal' as const,
      transition: 'all 200ms',
      textTransform: 'uppercase' as const
    }),
    content: {
      flex: 1,
      overflowY: 'auto' as const,
      padding: '16px',
      lineHeight: '1.6'
    },
    panel: {
      display: 'none' as const
    },
    panelActive: {
      display: 'block' as const
    },
    sectionTitle: {
      color: '#0f3',
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
      marginBottom: '8px',
      fontSize: '12px',
      fontWeight: 'bold' as const,
      textTransform: 'uppercase' as const
    },
    sectionDot: {
      width: '4px',
      height: '4px',
      backgroundColor: '#0f3',
      borderRadius: '50%' as const
    },
    sectionContent: {
      backgroundColor: '#1a1a2e',
      padding: '12px',
      marginBottom: '16px',
      border: '1px solid #333',
      borderRadius: '2px',
      whiteSpace: 'pre-wrap' as const,
      wordBreak: 'break-word' as const,
      fontSize: '12px'
    },
    footer: {
      padding: '8px 12px',
      borderTop: '1px solid #1a1a2e',
      backgroundColor: '#0f0f18',
      fontSize: '10px',
      color: '#666',
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center'
    },
    devInfo: {
      fontSize: '10px',
      color: '#0f3',
      fontWeight: 'bold' as const
    },
    historyList: {
      maxHeight: '200px',
      overflowY: 'auto' as const,
      marginTop: '8px',
      paddingTop: '8px',
      borderTop: '1px solid #333'
    },
    historyItem: {
      padding: '4px 8px',
      marginBottom: '4px',
      backgroundColor: '#0f0f18',
      border: '1px solid #222',
      cursor: 'pointer' as const,
      fontSize: '11px',
      color: '#888',
      transition: 'all 150ms'
    }
  };

  const playerLocation = state.locations?.find((l: any) => l.id === state.player.location);
  const locationName = playerLocation?.name ?? 'Unknown';
  const hour = state.hour ?? 12; // Phase 6: Direct property access (no type assertion)

  return (
    <div style={styles.container}>
      {/* Header */}
      <div style={styles.header}>
        <div>▪ Oracle View</div>
        <div style={{ fontSize: '11px', color: '#0f3' }}>
          {locationName} • Hour {hour}
        </div>
      </div>

      {/* Tab Bar */}
      <div style={styles.tabBar}>
        <button
          style={styles.tab(activePanel === 'atmosphere')}
          onClick={() => setActivePanel('atmosphere')}
        >
          Atmosphere
        </button>
        <button
          style={styles.tab(activePanel === 'visual')}
          onClick={() => setActivePanel('visual')}
        >
          Visual
        </button>
        <button
          style={styles.tab(activePanel === 'narrative')}
          onClick={() => setActivePanel('narrative')}
        >
          Narrative
        </button>
      </div>

      {/* Content Panel */}
      <div style={styles.content}>
        {/* Atmosphere Panel */}
        <div
          style={{
            ...styles.panel,
            ...(activePanel === 'atmosphere' ? styles.panelActive : {})
          }}
        >
          <div style={styles.sectionTitle}>
            <div style={styles.sectionDot} />
            Atmospheric Essence
          </div>
          <div style={styles.sectionContent}>
            {generatedContent.atmospheric}
          </div>
          {isDeveloperMode && (
            <div style={styles.sectionTitle}>
              <div style={{ ...styles.sectionDot, backgroundColor: '#666' }} />
              Debug Info
            </div>
          )}
          {isDeveloperMode && (
            <div style={styles.sectionContent}>
              Generated: {new Date(generatedContent.generatedAt).toLocaleTimeString()}
              {'\nSeed: ' + generatedContent.seed}
              {'\nLocation: ' + state.player.location}
            </div>
          )}
        </div>

        {/* Visual Panel */}
        <div
          style={{
            ...styles.panel,
            ...(activePanel === 'visual' ? styles.panelActive : {})
          }}
        >
          <div style={styles.sectionTitle}>
            <div style={styles.sectionDot} />
            Visual Composition
          </div>
          {generatedContent.visual && (
            <div>
              <div style={styles.sectionContent}>
                {generatedContent.visual.atmosphere}
              </div>
              <div style={styles.sectionTitle}>
                <div style={styles.sectionDot} />
                Detailed Description
              </div>
              <div style={styles.sectionContent}>
                {generatedContent.visual.detailedDescription}
              </div>
              <div style={styles.sectionTitle}>
                <div style={styles.sectionDot} />
                Color Tone
              </div>
              <div style={styles.sectionContent}>
                {generatedContent.visual.colorTone}
              </div>
            </div>
          )}
          {!generatedContent.visual && (
            <div style={styles.sectionContent}>
              Visual prompt generation in progress...
            </div>
          )}
        </div>

        {/* Narrative Panel */}
        <div
          style={{
            ...styles.panel,
            ...(activePanel === 'narrative' ? styles.panelActive : {})
          }}
        >
          <div style={styles.sectionTitle}>
            <div style={styles.sectionDot} />
            Recent Generations
          </div>
          <div style={styles.historyList}>
            {contentHistory.slice(0, 5).map((item, idx) => (
              <div key={`history-${item.generatedAt}`} style={styles.historyItem}>
                •{' '}
                {new Date(item.generatedAt).toLocaleTimeString()} at{' '}
                {item.seed}
              </div>
            ))}
          </div>
          <div style={{ ...styles.sectionTitle, marginTop: '12px' }}>
            <div style={styles.sectionDot} />
            Asset Generator Note
          </div>
          <div
            style={{
              ...styles.sectionContent,
              fontSize: '11px',
              color: '#888'
            }}
          >
            Visual prompts generated by assetGenerator are deterministic and
            can be used with image generation APIs for consistent UI art
            rendering across reruns.
          </div>
        </div>
      </div>

      {/* Footer */}
      <div style={styles.footer}>
        <div>M14: Deterministic Scene Generation</div>
        {isDeveloperMode && (
          <div style={styles.devInfo}>DEV MODE • Tick {state.tick}</div>
        )}
      </div>
    </div>
  );
};

export default OracleView;
