/**
 * Procedural Engine (Phase 2: Alpha)
 * 
 * Purpose: History-aware quest and encounter generation, replacing static weighted tables
 * 
 * Key Features:
 * - Generate quests based on world state and player history
 * - Create encounters that feel organic to the current narrative
 * - Track what the player has already experienced
 * - Avoid repetition while maintaining theme consistency
 * - Coordinate with AI DM Engine for pacing
 */

import type { WorldState, PlayerState } from './worldEngine';
import type { FactionConflict, Faction } from './factionEngine';
import { random } from './prng';

export interface ProceduralQuest {
  id: string;
  title: string;
  description: string;
  objectives: string[];
  reward: {
    gold: number;
    experience: number;
    itemIds: string[];
  };
  difficulty: number; // 1-10
  themes: string[]; // e.g., "rescue", "investigation", "combat"
  generatedAt: number;
}

export interface ProceduralEncounter {
  id: string;
  type: 'combat' | 'social' | 'exploration' | 'environmental';
  title: string;
  description: string;
  difficulty: number; // 1-10
  participants?: string[]; // NPC IDs or creature types
  generatedAt: number;
  location?: string;
}

/**
 * M24: Relic Issuance - Quest generated by sentient items
 * Items with high sentience can issue objectives to the player
 */
export interface RelicQuest extends ProceduralQuest {
  relicId: string;
  requiredAlignment?: number; // -100 to 100, must match relic's alignment
  sentience?: number; // 0-100, relic's consciousness level
}

/**
 * ALPHA_M3: Generate a procedural quest based on world state and faction conflicts
 * 
 * Quest themes are driven by:
 * 1. Active faction conflicts
 * 2. Player level and reputation
 * 3. Recently completed quests (avoid repetition)
 * 4. Location and NPC availability
 */
export function generateProceduralQuest(
  state: WorldState,
  theme?: string,
  conflict?: FactionConflict,
  relatedFaction?: Faction
): ProceduralQuest {
  const questId = `procedural-quest-${Date.now()}-${Math.floor(Math.random() * 10000)}`;
  const playerLevel = state.player?.level ?? 1;
  
  // Base difficulty scaled to player level
  const baseDifficulty = Math.min(10, Math.max(1, playerLevel));
  const difficultyVariation = Math.floor(random() * 3) - 1; // -1, 0, or +1
  const difficulty = Math.max(1, Math.min(10, baseDifficulty + difficultyVariation));

  // Determine quest type based on conflict
  let questType = theme ?? 'exploration';
  let title = 'A New Challenge Awaits';
  let description = 'The world has a quest for you...';
  let objectives: string[] = ['Discover the objective', 'Complete the objective'];
  const themes: string[] = [questType];

  if (conflict && relatedFaction) {
    const factionName = relatedFaction.name;
    
    switch (conflict.type) {
      case 'military': {
        // Military conflicts generate combat-focused quests
        const militaryQuests = [
          {
            title: `Scout for ${factionName}`,
            description: `${factionName} needs scouts to gather intelligence on enemy movements.`,
            objectives: ['Travel to a hostile location', 'Gather intelligence', 'Return to ${factionName}'],
            themes: ['reconnaissance', 'combat', 'scouting']
          },
          {
            title: `Defend ${factionName} Territory`,
            description: `Enemy forces threaten ${factionName}'s lands. Defend against intrusions.`,
            objectives: ['Patrol the territory', 'Defeat enemy scouts', 'Report back to leaders'],
            themes: ['combat', 'protection', 'defense']
          },
          {
            title: `Supply Run for ${factionName}`,
            description: `${factionName} needs supplies delivered to their front lines.`,
            objectives: ['Collect supplies', 'Transport supplies', 'Deliver to forward camp'],
            themes: ['delivery', 'support', 'logistics']
          }
        ];
        const selected = militaryQuests[Math.floor(random() * militaryQuests.length)];
        title = selected.title;
        description = selected.description;
        objectives = selected.objectives;
        themes.push(...selected.themes);
        break;
      }

      case 'diplomatic': {
        // Diplomatic conflicts generate messenger and negotiation quests
        const diplomaticQuests = [
          {
            title: `Messenger for ${factionName}`,
            description: `${factionName} needs a trustworthy messenger to carry an important letter.`,
            objectives: ['Receive the letter', 'Travel to the recipient', 'Deliver safely'],
            themes: ['messenger', 'negotiation', 'social']
          },
          {
            title: `Negotiate Peace`,
            description: `Tensions are high. ${factionName} seeks a brave negotiator.`,
            objectives: ['Meet both faction leaders', 'Present proposals', 'Broker agreement'],
            themes: ['negotiation', 'diplomacy', 'social']
          },
          {
            title: `Gather Neutral Testimony`,
            description: `${factionName} needs evidence to swing public opinion. Gather testimony from neutral parties.`,
            objectives: ['Interview neutral NPCs', 'Document their statements', 'Report findings'],
            themes: ['investigation', 'social', 'evidence']
          }
        ];
        const selected = diplomaticQuests[Math.floor(random() * diplomaticQuests.length)];
        title = selected.title;
        description = selected.description;
        objectives = selected.objectives;
        themes.push(...selected.themes);
        break;
      }

      case 'economic': {
        // Economic conflicts generate trade and sabotage quests
        const economicQuests = [
          {
            title: `Trade Monopoly for ${factionName}`,
            description: `${factionName} needs someone to corner the market on rare goods.`,
            objectives: ['Acquire rare goods', 'Disrupt competitor supply', 'Deliver to ${factionName}'],
            themes: ['trade', 'commerce', 'investigation']
          },
          {
            title: `Blackmail Information`,
            description: `${factionName} needs leverage against economic rivals.`,
            objectives: ['Find compromising evidence', 'Gather intelligence', 'Present to ${factionName}'],
            themes: ['espionage', 'investigation', 'social']
          },
          {
            title: `Merchant Escort`,
            description: `${factionName}'s merchant is carrying valuable goods. Protect the shipment.`,
            objectives: ['Meet the merchant', 'Defend during transport', 'Ensure safe arrival'],
            themes: ['protection', 'combat', 'commerce']
          }
        ];
        const selected = economicQuests[Math.floor(random() * economicQuests.length)];
        title = selected.title;
        description = selected.description;
        objectives = selected.objectives;
        themes.push(...selected.themes);
        break;
      }

      case 'infiltration': {
        // Infiltration conflicts generate spy and sabotage quests
        const infiltrationQuests = [
          {
            title: `Spy on ${factionName}'s Enemies`,
            description: `${factionName} needs covert intelligence from enemy leadership.`,
            objectives: ['Infiltrate enemy territory', 'Gather sensitive information', 'Report findings'],
            themes: ['espionage', 'infiltration', 'stealth']
          },
          {
            title: `Sabotage Enemy Supply`,
            description: `Weaken enemy capability by disrupting their supply lines.`,
            objectives: ['Locate enemy supplies', 'Disable or steal supplies', 'Report success'],
            themes: ['sabotage', 'stealth', 'mission']
          }
        ];
        const selected = infiltrationQuests[Math.floor(random() * infiltrationQuests.length)];
        title = selected.title;
        description = selected.description;
        objectives = selected.objectives;
        themes.push(...selected.themes);
        break;
      }

      case 'religious': {
        // Religious conflicts generate pilgrimage and conversion quests
        const religiousQuests = [
          {
            title: `Pilgrimage for ${factionName}`,
            description: `${factionName} seeks a pilgrim to visit sacred sites and spread their faith.`,
            objectives: ['Visit holy locations', 'Perform rituals', 'Spread word of ${factionName}'],
            themes: ['pilgrimage', 'religion', 'social']
          },
          {
            title: `Retrieve Sacred Relic`,
            description: `${factionName} believes rivals stole a sacred artifact. Retrieve it.`,
            objectives: ['Find the artifact', 'Overcome guardians', 'Return safely'],
            themes: ['heist', 'combat', 'religion']
          }
        ];
        const selected = religiousQuests[Math.floor(random() * religiousQuests.length)];
        title = selected.title;
        description = selected.description;
        objectives = selected.objectives;
        themes.push(...selected.themes);
        break;
      }
    }
  }

  // Calculate reward scaled to difficulty and player level
  const baseGold = playerLevel * 10;
  const difficultyMultiplier = 1 + (difficulty / 10);
  const gold = Math.floor(baseGold * difficultyMultiplier * (0.8 + random() * 0.4));
  const experience = Math.floor(playerLevel * difficulty * 50);
  
  return {
    id: questId,
    title,
    description,
    objectives,
    reward: {
      gold,
      experience,
      itemIds: []
    },
    difficulty,
    themes,
    generatedAt: Date.now()
  };
}

/**
 * M24: Generate a relic issuance quest - a sentient item commanding the player
 * Higher sentience = more assertive commands
 * Alignment can restrict what kinds of quests the relic will issue
 */
export function generateRelicQuest(
  state: WorldState,
  relicId: string,
  sentience: number = 50, // 0-100
  alignment: number = 0, // -100 to 100, -100 = evil, 0 = neutral, 100 = good
  preferredTheme?: string
): RelicQuest {
  const questId = `relic-issuance-${relicId}-${Date.now()}`;
  const playerLevel = state.player?.level ?? 1;

  // Sentience affects assertiveness and reward
  const difficulty = Math.max(1, Math.min(10, playerLevel + Math.floor((sentience - 50) / 10)));
  
  // Generate theme based on alignment and sentience
  let questType = preferredTheme ?? 'mission';
  let title =`${relicId}'s Task`;
  let description = `Your relic demands: ${questType}`;
  let objectives: string[] = ['Complete the relic\'s will'];
  const themes: string[] = [questType];

  // Alignment affects quest morality
  if (alignment > 50) {
    // Good relic - protective/rescue quests
    const goodQuests = [
      {
        title: 'Protect the Innocent',
        description: 'Your relic demands you defend those who cannot defend themselves.',
        objectives: ['Find endangered civilians', 'Defend them from threats', 'Ensure their safety'],
        themes: ['protection', 'rescue', 'good']
      },
      {
        title: 'Heal the Wounded',
        description: 'Your relic compels you to aid the suffering.',
        objectives: ['Locate the injured', 'Bring medical aid', 'Ensure recovery'],
        themes: ['healing', 'compassion', 'good']
      }
    ];
    const selected = goodQuests[Math.floor(random() * goodQuests.length)];
    title = selected.title;
    description = selected.description;
    objectives = selected.objectives;
    themes.push(...selected.themes);
  } else if (alignment < -50) {
    // Evil relic - conquest/domination quests
    const evilQuests = [
      {
        title: 'Assert Dominance',
        description: 'Your relic demands you prove your superiority over lesser beings.',
        objectives: ['Defeat powerful enemies', 'Claim territory', 'Display dominance'],
        themes: ['power', 'conquest', 'evil']
      },
      {
        title: 'Gather Dark Power',
        description: 'Your relic hungers for arcane energy and forbidden knowledge.',
        objectives: ['Collect forbidden artifacts', 'Learn dark rituals', 'Infuse the relic'],
        themes: ['corruption', 'power', 'evil']
      }
    ];
    const selected = evilQuests[Math.floor(random() * evilQuests.length)];
    title = selected.title;
    description = selected.description;
    objectives = selected.objectives;
    themes.push(...selected.themes);
  } else {
    // Neutral relic - self-interest/mystery quests
    const neutralQuests = [
      {
        title: 'Seek My Origin',
        description: 'Your relic demands you uncover the truth of its creation.',
        objectives: ['Research ancient history', 'Find the relic\'s maker', 'Uncover the truth'],
        themes: ['investigation', 'mystery', 'neutral']
      },
      {
        title: 'Grow Stronger',
        description: 'Your relic requires power to fulfill its potential.',
        objectives: ['Absorb magical energy', 'Defeat powerful foes', 'Increase relic power'],
        themes: ['growth', 'power', 'neutral']
      }
    ];
    const selected = neutralQuests[Math.floor(random() * neutralQuests.length)];
    title = selected.title;
    description = selected.description;
    objectives = selected.objectives;
    themes.push(...selected.themes);
  }

  // Sentience affects reward - more conscious items demand more reasonable payment
  const baseFactor = sentience / 50; // 0-2 scale
  const baseGold = playerLevel * 15;
  const gold = Math.floor(baseGold * baseFactor * (0.7 + random() * 0.5));
  const experience = Math.floor(playerLevel * difficulty * 40);

  return {
    id: questId,
    relicId,
    title,
    description,
    objectives,
    reward: {
      gold,
      experience,
      itemIds: []
    },
    difficulty,
    themes,
    sentience,
    requiredAlignment: alignment,
    generatedAt: Date.now()
  };
}

/**
 * ALPHA_M3: Generate a procedural encounter based on location, faction control, and world state
 * 
 * Encounter scaling considers:
 * 1. Location faction control (hostile/friendly territory affects encounter type)
 * 2. Player level
 * 3. Current faction conflicts
 * 4. Environmental factors
 */
export function generateProceduralEncounter(
  state: WorldState,
  locationId: string,
  type?: 'combat' | 'social' | 'exploration' | 'environmental',
  controllingFactionId?: string,
  playerFactionReputation?: Record<string, number>
): ProceduralEncounter {
  const encounterId = `procedural-encounter-${Date.now()}-${Math.floor(Math.random() * 10000)}`;
  const playerLevel = state.player?.level ?? 1;
  const location = state.locations?.find(l => l.id === locationId);

  // Determine encounter type based on faction territory
  let encounterType = type ?? 'exploration';
  let title = 'An Unexpected Meeting';
  let description = 'Something interesting happens here...';
  let difficulty = playerLevel;
  let participants: string[] = [];

  // If location is controlled by a faction hostile to player, increase combat encounters
  if (controllingFactionId && playerFactionReputation) {
    const playerRep = playerFactionReputation[controllingFactionId] ?? 0;
    
    if (playerRep < -30) {
      // Hostile territory - more combat encounters
      const combatEncounters = [
        { title: 'Ambush!', description: 'Enemy soldiers bar your path.', difficulty: 2 },
        { title: 'Territorial Guards', description: 'Faction enforcers challenge your presence.', difficulty: 1 },
        { title: 'Monster Swarm', description: 'Neglected borders have drawn dangerous creatures.', difficulty: 2 }
      ];
      const selected = combatEncounters[Math.floor(random() * combatEncounters.length)];
      title = selected.title;
      description = selected.description;
      difficulty = playerLevel + selected.difficulty;
      encounterType = 'combat';
    } else if (playerRep > 30) {
      // Friendly territory - social and discovery encounters
      const friendlyEncounters = [
        { title: 'Warm Welcome', description: 'Faction members offer hospitality and information.', type: 'social' as const },
        { title: 'Hidden Treasure', description: 'You discover a secret cache left by faction allies.', type: 'exploration' as const },
        { title: 'Festival Gathering', description: 'The faction is celebrating. Join in?', type: 'social' as const }
      ];
      const selected = friendlyEncounters[Math.floor(random() * friendlyEncounters.length)];
      title = selected.title;
      description = selected.description;
      encounterType = selected.type;
      difficulty = Math.max(1, playerLevel - 1);
    } else {
      // Neutral territory - mixed encounters
      const neutralEncounters = [
        { title: 'Curious Traveler', description: 'An NPC asks about your business here.', type: 'social' as const },
        { title: 'Local Wildlife', description: 'Wild creatures roam this neutral ground.', type: 'combat' as const },
        { title: 'Ancient Ruins', description: 'Crumbling structures hint at forgotten history.', type: 'exploration' as const }
      ];
      const selected = neutralEncounters[Math.floor(random() * neutralEncounters.length)];
      title = selected.title;
      description = selected.description;
      encounterType = selected.type;
    }
  }

  // Environmental encounters based on season/weather
  if (!type && state.weather) {
    if (state.weather === 'rain') {
      const rainEncounters = ['Shelter from the rain', 'Mudslide danger nearby!', 'Washed-out path'];
      title = rainEncounters[Math.floor(random() * rainEncounters.length)];
      encounterType = 'environmental';
    } else if (state.weather === 'snow') {
      const snowEncounters = ['Blizzard hazard', 'Frozen passage', 'Desperate frozen travelers'];
      title = snowEncounters[Math.floor(random() * snowEncounters.length)];
      encounterType = 'environmental';
    }
  } else if (!type && state.season === 'winter') {
    const winterEncounters = ['Ice storm approaching', 'Frozen ruins', 'Desperate travelers'];
    title = winterEncounters[Math.floor(random() * winterEncounters.length)];
    encounterType = 'environmental';
  }

  return {
    id: encounterId,
    type: encounterType,
    title,
    description,
    difficulty: Math.max(1, Math.min(10, difficulty)),
    participants,
    generatedAt: Date.now(),
    location: locationId
  };
}

/**
 * Track generation patterns to avoid repetition
 */
export function getGenerationHistory(state: WorldState, limit: number = 10): ProceduralQuest[] {
  // STUB: Phase 2 implementation will:
  // 1. Query quest history from state.quests
  // 2. Filter for procedurally generated ones
  // 3. Return most recent N quests
  // 4. Use this to avoid repeating similar content
  
  return [];
}

/**
 * Ensure generated content respects thematic consistency
 */
/**
 * Generate a pool of quests from active faction conflicts
 * Called when NPCs need to offer quests
 */
export function generateQuestPoolFromConflicts(
  state: WorldState,
  conflicts: FactionConflict[],
  factions: Faction[],
  count: number = 3
): ProceduralQuest[] {
  const quests: ProceduralQuest[] = [];
  const maxAttempts = count * 3; // Prevent infinite loops
  let attempts = 0;

  while (quests.length < count && attempts < maxAttempts) {
    attempts++;

    // Pick a random active conflict
    const activeConflicts = conflicts.filter(c => c.active);
    if (activeConflicts.length === 0) break;

    const conflict = activeConflicts[Math.floor(random() * activeConflicts.length)];
    
    // Pick one of the faction participants
    const factionId = conflict.factionIds[Math.floor(random() * conflict.factionIds.length)];
    const faction = factions.find(f => f.id === factionId);
    
    if (!faction) continue;

    // Generate quest for this conflict
    const quest = generateProceduralQuest(state, undefined, conflict, faction);
    
    // Check if we already have a very similar quest
    const isDuplicate = quests.some(q => 
      q.title === quest.title || 
      q.themes.some(t => quest.themes.includes(t)) && q.difficulty === quest.difficulty
    );

    if (!isDuplicate) {
      quests.push(quest);
    }
  }

  return quests;
}

/**
 * ALPHA_M14: Generate "Alpha the Bound One" - Rare Emergent Entity
 * 
 * Trigger: High Paradox (> 75) + Corrupted Biome + Night
 * Alpha reads from canonJournal to reference player history
 * She is a legendary entity that observes the player and speaks their personal narrative
 * 
 * @returns Encounter object if Alpha should manifest, null otherwise
 */
export function checkAlphaTheBindOneManifest(state: WorldState): ProceduralEncounter | null {
  // Check trigger conditions
  const paradoxLevel = state.player?.temporalDebt ?? 0;
  if (paradoxLevel <= 75) {
    return null; // Insufficient paradox
  }

  // Check location (corrupted biome)
  const playerLocation = state.locations?.find(l => l.id === state.player.location);
  const isCorrupted = playerLocation?.biome === 'corrupted';
  if (!isCorrupted) {
    return null; // Wrong biome
  }

  // Check time (night only)
  const hour = state.hour ?? 12;
  const isNight = hour >= 20 || hour < 6;
  if (!isNight) {
    return null; // Wrong time
  }

  // All conditions met - Alpha manifests!
  // Retrieve player's most impactful narrative pivots
  const journal = (state as any).canonJournal as { narrativePivots?: any[] } | undefined;
  const pivots = journal?.narrativePivots ?? [];
  const topPivots = pivots.slice(-3); // Last 3 most recent high-impact moments

  // Generate Alpha's dialogue referencing player history
  let alphaDialogue = `*A shimmering figure materializes before you—a woman of impossible grace, her eyes containing infinite reflections.*\n\n"Greetings, Time-Walker. I am Alpha, Bound One of the Paradox Currents.\n\n`;

  if (topPivots.length > 0) {
    alphaDialogue += `I have observed you across the fractured timeline. I remember:\n`;
    topPivots.forEach((pivot: any, idx: number) => {
      alphaDialogue += `\n${idx + 1}. "${pivot.description || 'A moment of significance'}"`;
    });
    alphaDialogue += `\n\nYour choices echo through the fabric of reality itself. The paradox you carry is no accident—it is your own making.\n`;
  } else {
    alphaDialogue += `Your time-debt precedes you. The world bends around your presence.\n`;
  }

  alphaDialogue += `\nWhat will you ask of me, Paradox-Bearer?`;

  return {
    id: `alpha-encounter-${state.tick ?? 0}`,
    type: 'social',
    title: 'Alpha the Bound One',
    description: alphaDialogue,
    difficulty: 8, // High difficulty - she's legendary
    participants: ['alpha-bound-one', 'player'],
    generatedAt: Date.now(),
    location: state.player.location
  };
}

export function validateThemicConsistency(
  quest: ProceduralQuest,
  state: WorldState
): boolean {
  // ALPHA_M3: Basic thematic validation
  // 1. Check if quest themes are recognized
  // 2. Validate difficulty is in range
  // 3. Ensure objectives are non-empty
  
  const validThemes = [
    'exploration', 'combat', 'social', 'mission', 'rescue',
    'investigation', 'espionage', 'delivery', 'protection', 'trade',
    'negotiation', 'diplomacy', 'heist', 'pilgrimage', 'religion',
    'reconnaissance', 'scouting', 'logistics', 'commerce', 'evidence',
    'stealth', 'support', 'defense', 'good', 'evil', 'neutral',
    'power', 'conquest', 'corruption', 'growth', 'healing', 'compassion',
    'mystery', 'investigation'
  ];

  const allThemesValid = quest.themes.every(t => validThemes.includes(t));
  const difficultyValid = quest.difficulty >= 1 && quest.difficulty <= 10;
  const objectivesValid = quest.objectives.length > 0;
  
  return allThemesValid && difficultyValid && objectivesValid;
}

/**
 * Connect procedural content to world events
 * Updates quest descriptions to reference recent events
 */
export function linkToWorldEvents(quest: ProceduralQuest, state: WorldState): ProceduralQuest {
  // ALPHA_M3: Reference recent faction conflicts in quest description
  const recentConflicts = (state.factionConflicts || [])
    .filter(c => c.active)
    .slice(0, 2); // Last 2 relevant conflicts

  if (recentConflicts.length > 0 && quest.description.includes('Tensions')) {
    // Quest is already tied to conflicts
    return quest;
  }

  // Could add event references here, but for now return as-is
  return quest;
}

/**
 * Use AI to enhance quest narratives (stub for Phase 3)
 */
export async function generateQuestNarrative(quest: ProceduralQuest): Promise<string> {
  // ALPHA_M3: For now, return generated description
  // Phase 3 could integrate with LLM services
  
  return quest.description;
}
